<Workspace Version="1.3.2.2480" X="-616.023898068511" Y="116.983492726942" zoom="1.27771698410772" ScaleFactor="1" Name="3dSectionBox_by Selected Elements " Description="sets the 3d section box to actively select elements " ID="9661425a-0cad-426e-8187-2e5f9dc8226b" Category="ArupBimSF.Revit.Views &amp; Sheets">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7acc10e8-2782-40b8-9727-e230012b5542" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1143.20101203148" y="64.8479409148328" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc =  DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIDocument
app = DocumentManager.Instance.CurrentUIApplication.Application
uiapp = DocumentManager.Instance.CurrentUIApplication

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import *
output = []
postcmd = RevitCommandId.LookupPostableCommandId(PostableCommand.SelectionBox)
if IN[0] == True:
	uiapp.PostCommand(postcmd)
	output = True
else :
	output = 'Set RunIt to true'
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="372767f3-0cd9-4447-8673-fb8ebed6ab9f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1312.73095128989" y="128.597206854797" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Result" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="74b50923-5ef0-45d5-b85e-a3f78d0b281e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="928.6" y="128" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RunIt : bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7acc10e8-2782-40b8-9727-e230012b5542" start_index="0" end="372767f3-0cd9-4447-8673-fb8ebed6ab9f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="74b50923-5ef0-45d5-b85e-a3f78d0b281e" start_index="0" end="7acc10e8-2782-40b8-9727-e230012b5542" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>