<Workspace Version="1.3.2.2480" X="-15.0385663489724" Y="111.181878268911" zoom="0.931811528498331" ScaleFactor="1" Name="Copy_ElementsFromDocument" Description="copy elements from  one document to another" ID="acb8c12a-8f3b-4695-abcc-d2cb2d116916" Category="ArupBimSF.^TestingGrounds">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f0f220ad-64a0-4f14-b802-36a91de5c55a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1380" y="330" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Based on a node originally from Dimitar Venkov
import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
doc1 = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

from System.Collections.Generic import*


ele = List[ElementId](IN[0])
link1 = IN[1]

try:
	TransactionManager.Instance.EnsureInTransaction(doc)
	newId = ElementTransformUtils.CopyElements(link1, ele, doc1, None, CopyPasteOptions() )
	TransactionManager.Instance.TransactionTaskDone()
	res1 = [doc.GetElement(newId[i]).ToDSType(False) for i in xrange(len(newId) )]
except: 	
	res1 = 'The process failed. If you are copying from more than one document, change the lacing to longest.'

OUT = res1</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="30101f87-c2d7-444b-a09f-276041d5e757" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="951" y="385" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The document you are copying from.&#xD;&#xA;document" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="11c21757-16f9-4c1a-b869-7e4a79d7e2d9" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1602" y="330" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="copied" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="ab4481b4-c944-43b6-8a3a-0e3bde4c98c9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="951" y="301" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

items = UnwrapElement(IN[0])
elementlist = list()
booleans = list()
for item in items:
	try:
		elementlist.append(item.Id)
	except:
		elementlist.append(None)
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="b35f1b6b-608e-430a-be54-be3b722c2b92" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="649" y="305.213333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="940759d4-1da3-4678-9da0-9a0cd8d85212" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="325.122173436441" y="251.633793859439" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The elements to be copied&#xD;&#xA;elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f0f220ad-64a0-4f14-b802-36a91de5c55a" start_index="0" end="11c21757-16f9-4c1a-b869-7e4a79d7e2d9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="30101f87-c2d7-444b-a09f-276041d5e757" start_index="0" end="f0f220ad-64a0-4f14-b802-36a91de5c55a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ab4481b4-c944-43b6-8a3a-0e3bde4c98c9" start_index="0" end="f0f220ad-64a0-4f14-b802-36a91de5c55a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b35f1b6b-608e-430a-be54-be3b722c2b92" start_index="0" end="ab4481b4-c944-43b6-8a3a-0e3bde4c98c9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="940759d4-1da3-4678-9da0-9a0cd8d85212" start_index="0" end="b35f1b6b-608e-430a-be54-be3b722c2b92" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>