<Workspace Version="1.3.2.2480" X="-92.586230382625" Y="62.4713507603125" zoom="0.798825425049557" ScaleFactor="1" Name="Db_ElementTypes_Get All" Description="get all element type classes" ID="00ba9825-e614-4b2d-823a-ebfbde0f3a28" Category="ArupBimSF.Revit_Db">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d786137b-1995-410b-92b7-444285c24db9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.SortByKey" x="1159.28759331021" y="424.806885459728" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.SortByKey@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="9b36ee9e-5fa6-4fda-aab8-41f7bb5d8b98" type="PythonNodeModels.PythonNode" nickname="Python Script" x="678.800248707752" y="435.192222968037" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)
import System.Reflection
import System.AppDomain

rAssembly = [x for x in System.AppDomain.CurrentDomain.GetAssemblies() if x.GetName().Name == 'RevitAPI'][0]
rElement = [x for x in rAssembly.GetTypes() if x.Name == 'Element' and x.Namespace == 'Autodesk.Revit.DB'][0]
OUT = [x for x in rAssembly.GetTypes() if x.IsClass and x.Namespace == 'Autodesk.Revit.DB' and x.IsSubclassOf(rElement)]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b7b7419f-1f74-4c65-aa9e-65a9357496ad" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1514.27589610436" y="424.166827219885" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elementTypes" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="d2ba48e4-a5e5-43bf-a5bd-ec6b8cba7e98" type="PythonNodeModels.PythonNode" nickname="Python Script" x="899.290934148159" y="510.021209742689" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

faminsts = IN[0]
elementlist = list()
for item in faminsts:
	try:
		n = UnwrapElement(item).Name
	except:
		# Use a built-in property of (wrapped) Dynamo elements for family symbols instead
		try:
			n = item.Name
		except:
			# maybe it's a parameter name
			try:
				n = item.Definition.Name
			except:
				n = []
	elementlist.append(n)
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="fbfa9bf1-20a5-4afc-a623-6cb1c89f7739" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1542.78843322326" y="508.62488509365" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="TypeNames" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d786137b-1995-410b-92b7-444285c24db9" start_index="0" end="b7b7419f-1f74-4c65-aa9e-65a9357496ad" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d786137b-1995-410b-92b7-444285c24db9" start_index="1" end="fbfa9bf1-20a5-4afc-a623-6cb1c89f7739" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9b36ee9e-5fa6-4fda-aab8-41f7bb5d8b98" start_index="0" end="d786137b-1995-410b-92b7-444285c24db9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9b36ee9e-5fa6-4fda-aab8-41f7bb5d8b98" start_index="0" end="d2ba48e4-a5e5-43bf-a5bd-ec6b8cba7e98" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d2ba48e4-a5e5-43bf-a5bd-ec6b8cba7e98" start_index="0" end="d786137b-1995-410b-92b7-444285c24db9" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>