<Workspace Version="1.3.2.2480" X="48" Y="131" zoom="1" ScaleFactor="1" Name="DetachAndSaveNewCentral_ByFilePath" Description="detaches and saves a central model from an input file path" ID="fecfe817-d55b-4746-8625-2c07e041f2ac" Category="ArupBimSF.Revit.Directory">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f048e486-f2bd-4aaa-967b-f31203fe3daf" type="PythonNodeModels.PythonNode" nickname="Python Script" x="769.428927774132" y="219.669877162485" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

if isinstance(IN[0], list):
	files = IN[0]
else:
	files = [IN[0]]

version = "v" + app.VersionNumber

options = OpenOptions()
options.DetachFromCentralOption = DetachFromCentralOption.DetachAndPreserveWorksets

worksharingOptions = WorksharingSaveAsOptions()
worksharingOptions.SaveAsCentral = True

SaveOptions = SaveAsOptions()
SaveOptions.SetWorksharingOptions(worksharingOptions)

for file in files:
	modelpath = FilePath(file)
	newdoc = app.OpenDocumentFile(modelpath,options)
	newfile = file[:-4] + version + ".rvt"
	newdoc.SaveAs(newfile,SaveOptions)
	newdoc.Close(False)

OUT = 0</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b3621a89-3e22-40b6-8740-9e48a53b9646" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="613.215804226993" y="209.918633695611" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="file path" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b3621a89-3e22-40b6-8740-9e48a53b9646" start_index="0" end="f048e486-f2bd-4aaa-967b-f31203fe3daf" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>