<Workspace Version="1.3.2.2480" X="-106.4875" Y="197.87" zoom="1.1575" ScaleFactor="1" Name="Element_CopyFromLinkedDocument" Description="copy an element from a linked document into current document" ID="43631e25-5e9e-4b1a-8fe4-323a1efdc68d" Category="ArupBimSF.^TestingGrounds">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9a62fe77-4367-4880-b771-6211a4d21adb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="903.410754536825" y="120.29373650108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="local element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="7b8c2057-9728-4026-8a61-427e8f826ac6" type="PythonNodeModels.PythonNode" nickname="Python Scrpit" x="708.067332372456" y="123.446193184068" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

def singleton(x):
	if hasattr(x,'__iter__'): return x[0]
	else : return x

def tolist(x):
	if hasattr(x,'__iter__'): return x
	else : return [x]


linkInst = UnwrapElement(singleton(IN[0]) )
elements = UnwrapElement(tolist(IN[1]) )

linkDoc = linkInst.GetLinkDocument()
tf1 = linkInst.GetTotalTransform()
eId = List[ElementId]()
for e in elements:
	try:
		id1 = e.Id
	except:
		continue
	eId.Add(id1)

TransactionManager.Instance.EnsureInTransaction(doc)
copy = ElementTransformUtils.CopyElements(linkDoc, eId, doc, tf1, None)
TransactionManager.Instance.TransactionTaskDone()

OUT = [doc.GetElement(i).ToDSType(False) for i in copy]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1c043af9-f220-4a5f-bbb9-029190294bf3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="449.428023517165" y="131.221571153831" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="LinkInstance:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="42ebd3e7-161a-4598-8079-e6012fb3b2c4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="455.218142548596" y="289.957578188122" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7b8c2057-9728-4026-8a61-427e8f826ac6" start_index="0" end="9a62fe77-4367-4880-b771-6211a4d21adb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1c043af9-f220-4a5f-bbb9-029190294bf3" start_index="0" end="7b8c2057-9728-4026-8a61-427e8f826ac6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="42ebd3e7-161a-4598-8079-e6012fb3b2c4" start_index="0" end="7b8c2057-9728-4026-8a61-427e8f826ac6" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>