<Workspace Version="1.3.2.2480" X="-207.666847187851" Y="192.184913432984" zoom="0.931811528498331" ScaleFactor="1" Name="Framing_DisallowJoins" Description="Disallow Joins of input structural framing" ID="92d06cbe-60d2-47bd-8c09-60b58f6037aa" Category="ArupBimSF.Revit.Structural">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d194c157-7e0d-42db-91ce-33c9d2fe04d0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="820" y="61.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="d63d30f6-cbf2-4583-a1bb-5d06383100c3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="974.4" y="105" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Unwrap
input = UnwrapElement( IN[0] )
DisallowAtStart= IN[1]
DisallowAtEnd= IN[2]
elements = []
#force input into list
try:
	for e in input:
		if e.Category.Name == "Structural Framing":
			elements.append(e)
except:
	if input.Category.Name == "Structural Framing": 
		elements.append(input)
	

	
# Start Transaction
doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(doc)

for e in elements:
	if DisallowAtStart:
		Autodesk.Revit.DB.Structure.StructuralFramingUtils.DisallowJoinAtEnd(e, 0)
	else:
		Autodesk.Revit.DB.Structure.StructuralFramingUtils.AllowJoinAtEnd(e, 0)
	if DisallowAtEnd:
		Autodesk.Revit.DB.Structure.StructuralFramingUtils.DisallowJoinAtEnd(e, 1)
	else:
		Autodesk.Revit.DB.Structure.StructuralFramingUtils.AllowJoinAtEnd(e, 1)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

# Wrap
OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e95d8d37-91df-46f7-8e8d-7c6b5a6f1d75" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1161" y="103.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="45b52a41-bcf4-4a86-82fe-47d2d8d9355f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="708" y="130.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="DisallowAtStart: bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5e09d608-510c-47e9-861c-3f53ac0c5eef" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="707" y="194.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="DisallowAtEnd: bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d194c157-7e0d-42db-91ce-33c9d2fe04d0" start_index="0" end="d63d30f6-cbf2-4583-a1bb-5d06383100c3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d63d30f6-cbf2-4583-a1bb-5d06383100c3" start_index="0" end="e95d8d37-91df-46f7-8e8d-7c6b5a6f1d75" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="45b52a41-bcf4-4a86-82fe-47d2d8d9355f" start_index="0" end="d63d30f6-cbf2-4583-a1bb-5d06383100c3" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5e09d608-510c-47e9-861c-3f53ac0c5eef" start_index="0" end="d63d30f6-cbf2-4583-a1bb-5d06383100c3" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>