<Workspace Version="1.3.2.2480" X="-103" Y="23" zoom="1" ScaleFactor="1" Name="Get Param_as Project Units" Description="^^^new_Use this one to learn how to wrtie the filter_by parameter at index in python" ID="f9a9ba7c-0546-40b9-9086-dea8fa530606" Category="ArupBimSF.^TestingGrounds">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d33f953a-b98f-4686-b493-793678c8fed3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1063" y="345" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Values" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="a35bf3da-a5df-4129-b1e4-aba69c43964a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="818" y="316" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
	element = UnwrapElement(IN[0])
else:
	element = [UnwrapElement(IN[0])]
name = IN[1]
listout = []

def checkParameter(param):
	for p in param:
		internal = p.Definition
		if internal.BuiltInParameter != BuiltInParameter.INVALID:
			return p
	return param[0]

for e in element:
	param = e.GetParameters(name)
	if len(param) == 0:
		listout.append(None)
	else:
		p = checkParameter(param)
		if p.StorageType == StorageType.String:
			listout.append(p.AsString())
		elif p.StorageType == StorageType.ElementId:
			elem = doc.GetElement(p.AsElementId())
			listout.append(elem)
		elif p.StorageType == StorageType.Double:
			ProjectUnits = p.DisplayUnitType
			newval = UnitUtils.ConvertFromInternalUnits(p.AsDouble(),ProjectUnits)
			listout.append(newval)
		else:
			listout.append(p.AsInteger())
	

#Assign your output to the OUT variable.
OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7b265b7b-d126-4bf2-87c4-ec5ec3cc3b72" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="548" y="309" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a1216c1b-1cfb-47c8-8185-5cfd74e3fba9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="528" y="481" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ParameterName : string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a35bf3da-a5df-4129-b1e4-aba69c43964a" start_index="0" end="d33f953a-b98f-4686-b493-793678c8fed3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7b265b7b-d126-4bf2-87c4-ec5ec3cc3b72" start_index="0" end="a35bf3da-a5df-4129-b1e4-aba69c43964a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a1216c1b-1cfb-47c8-8185-5cfd74e3fba9" start_index="0" end="a35bf3da-a5df-4129-b1e4-aba69c43964a" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>