<Workspace Version="1.3.2.2480" X="-355.934835807222" Y="-348.717210156046" zoom="1.78359936238281" ScaleFactor="1" Name="Get_FamilyTypes_FE" Description="Outputs all family types of  the active Family doc in the family editor.  Also outputs the Active Famliy Type._!!FE" ID="ba304101-a1b1-43eb-a335-0cb992bf6b56" Category="ArupBimSF.Revit.FamilyEditor">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="db1987e0-fafa-4dda-abaf-cda809dbad69" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="894.407821229051" y="304.347383498379" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="familyTypes" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="fdf46195-f48f-4569-8838-abe4c8402acd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="692.802036631826" y="304.98583198189" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
elementlist = list()
if doc.IsFamilyDocument:
	for ftype in doc.FamilyManager.Types:
		elementlist.append(ftype)
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="96ed1c64-24d8-4b01-b019-cfec848b1e36" type="PythonNodeModels.PythonNode" nickname="Python Script" x="698.106401778066" y="435.365216193735" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
if doc.IsFamilyDocument:
	OUT = doc.FamilyManager.CurrentType
else: OUT = None</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f2735aeb-b4a5-4388-b369-6f63d68d7333" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="908.322103068467" y="432.561896061729" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ActiveType" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a1f3271b-5247-4c47-a9a3-7505f64cabe0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="381.49426138629" y="313.521985714543" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Refresh : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fdf46195-f48f-4569-8838-abe4c8402acd" start_index="0" end="db1987e0-fafa-4dda-abaf-cda809dbad69" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96ed1c64-24d8-4b01-b019-cfec848b1e36" start_index="0" end="f2735aeb-b4a5-4388-b369-6f63d68d7333" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a1f3271b-5247-4c47-a9a3-7505f64cabe0" start_index="0" end="fdf46195-f48f-4569-8838-abe4c8402acd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a1f3271b-5247-4c47-a9a3-7505f64cabe0" start_index="0" end="96ed1c64-24d8-4b01-b019-cfec848b1e36" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>