<Workspace Version="1.3.2.2480" X="-37.2581585536575" Y="1.8724540466116" zoom="1.130842140625" ScaleFactor="1" Name="Get_Elements_BySelectInRevit" Description="Selects input elements in revit_!se" ID="fc407d94-4ade-4097-8c2b-a2b2ff97fb2f" Category="ArupBimSF.Revit.Element_Selectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="3e926752-c9d8-4d62-b92a-726fe4a81790" type="PythonNodeModels.PythonNode" nickname="Python Script" x="753.946955034413" y="322.791174918386" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import ElementId
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI.Selection import *

clr.AddReference("System")
from System.Collections.Generic import List as cList

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

elements = UnwrapElement(tolist(IN[0]) )
ids1 = []
for i in xrange(len(elements)):
	try:(ids1.append(elements[i].Id))
	except: pass
ids2 = cList[ElementId](ids1)
uidoc.Selection.SetElementIds(ids2)
OUT = "%s elements selected in Revit." %ids2.Count</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5109dc70-25a9-449e-b88d-f8a9360f918f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="983.884649671857" y="321.191463869749" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="success?" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d7e65c33-6c63-4b35-b6de-07857bedf359" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="472.563502152711" y="309.026551566442" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elements_In:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="41818ee9-b8de-48b1-bbd7-d6fee94a3ed6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="468.002159827214" y="421.354744152756" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Reset:bool = true;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3e926752-c9d8-4d62-b92a-726fe4a81790" start_index="0" end="5109dc70-25a9-449e-b88d-f8a9360f918f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d7e65c33-6c63-4b35-b6de-07857bedf359" start_index="0" end="3e926752-c9d8-4d62-b92a-726fe4a81790" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="41818ee9-b8de-48b1-bbd7-d6fee94a3ed6" start_index="0" end="3e926752-c9d8-4d62-b92a-726fe4a81790" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>