<Workspace Version="1.3.2.2480" X="167.666382138632" Y="419.333318605293" zoom="1.1113575327695" ScaleFactor="1" Name="Get_Element_Category+" Description="gets the category and category name of input elements. Gets categories from types, and other elements such as worksets which the OOTB cannot." ID="0c3ff8ab-99a8-4dbc-aeb2-5b7c528d66eb" Category="ArupBimSF.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.FromObject guid="89fd9501-83d2-489f-ba5a-ccd7244e2cd8" type="CoreNodeModels.FromObject" nickname="String from Object" x="486.827606834837" y="93.3573964961144" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.FromObject>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="12360d99-fcd7-4fe9-ace7-71a77e5127b8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="83.8285822068473" y="-41.2270036561272" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ElementsIn" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2eb8f4c2-aece-4ff8-956b-3be92eee6405" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="531.257836099086" y="-36.4704127535961" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d07bb83b-8fb8-4feb-9414-6813104398d0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="742.599348812662" y="92" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="AsString" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="ee8aab92-af35-4a33-8248-61cff8c03ec5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="260.26854670194" y="-35.7091126151972" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

items = UnwrapElement(IN[0])
elementlist = list()
for item in items:
	objtype = item.GetType().ToString()
	try:
		if objtype == "Autodesk.Revit.DB.ViewSchedule":
			elementlist.append(Revit.Elements.Category.ById(item.Definition.CategoryId.IntegerValue))
		elif objtype == "Autodesk.Revit.DB.Family":
			elementlist.append(Revit.Elements.Category.ById(item.FamilyCategoryId.IntegerValue))
		elif objtype == "Autodesk.Revit.DB.GraphicsStyle":
			elementlist.append(Revit.Elements.Category.ById(item.GraphicsStyleCategory.Id.IntegerValue))
		else:
			elementlist.append(Revit.Elements.Category.ById(item.Category.Id.IntegerValue))
	except:
		elementlist.append(None)

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="89fd9501-83d2-489f-ba5a-ccd7244e2cd8" start_index="0" end="d07bb83b-8fb8-4feb-9414-6813104398d0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="12360d99-fcd7-4fe9-ace7-71a77e5127b8" start_index="0" end="ee8aab92-af35-4a33-8248-61cff8c03ec5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ee8aab92-af35-4a33-8248-61cff8c03ec5" start_index="0" end="2eb8f4c2-aece-4ff8-956b-3be92eee6405" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ee8aab92-af35-4a33-8248-61cff8c03ec5" start_index="0" end="89fd9501-83d2-489f-ba5a-ccd7244e2cd8" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>