<Workspace Version="1.3.2.2480" X="48" Y="205" zoom="1" ScaleFactor="1" Name="Get_Viewports_FromSheets" Description="Get the Viewports from input sheets" ID="ac2f146a-d73b-4cb9-a2a2-974511512b9f" Category="ArupBimSF.Revit.Views &amp; Sheets">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="b238aca1-c3a4-4ad9-bc49-b0e83a4bdf35" type="PythonNodeModels.PythonNode" nickname="Python Script" x="722" y="20" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

sheets = []
for i in IN[0]:
	sheets.append(UnwrapElement(i))

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

vplist=[]
for v in sheets:
	vp=[]
	a=v.GetAllViewports()
	for i in a:
		b=doc.GetElement(i)
		vp.append(b)
	vplist.append(vp)
			

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT=vplist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="31def22b-f395-48ec-a2ec-2ae03dc03ec4" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="953" y="20" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Viewports" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9584d544-e713-43cc-8b7d-5eb35cec38d4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="547" y="20" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Sheet" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b238aca1-c3a4-4ad9-bc49-b0e83a4bdf35" start_index="0" end="31def22b-f395-48ec-a2ec-2ae03dc03ec4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9584d544-e713-43cc-8b7d-5eb35cec38d4" start_index="0" end="b238aca1-c3a4-4ad9-bc49-b0e83a4bdf35" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>