<Workspace Version="1.3.2.2480" X="-148" Y="159" zoom="1" ScaleFactor="1" Name="Get_DuctOrPipe_SystemElements" Description="get all the associated elements of input mep systems" ID="2231730c-c8f7-4f72-b55b-a7e41f7b12b2" Category="ArupBimSF.Revit.Mep_Systems">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3c92dd00-e8d1-4044-ac98-6c4c947d2d39" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="996" y="287" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="b234a312-aad9-4234-a388-2d24655d74c4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="792" y="276" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

#All credit for the ProcessList function goes to Archi-lab author Konrad Sobon
def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

def Unwrap(e):
	return UnwrapElement(e)

	
if isinstance(IN[0], list):
	systems = ProcessList(Unwrap, IN[0])
	toggle = 0
else:
	systems = [Unwrap(IN[0])]
	toggle = 1
#The inputs to this node will be stored as a list in the IN variables.
def systemElements(systems):
	elements = systems.Elements
	sublist = []
	for x in elements:
		sublist.append(x)
	return sublist

result = ProcessList(systemElements,systems)
OUT = result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9f37e7e8-6362-4e33-8fda-701a919525f8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="603" y="278" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Systems" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b234a312-aad9-4234-a388-2d24655d74c4" start_index="0" end="3c92dd00-e8d1-4044-ac98-6c4c947d2d39" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f37e7e8-6362-4e33-8fda-701a919525f8" start_index="0" end="b234a312-aad9-4234-a388-2d24655d74c4" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>