<Workspace Version="1.3.2.2480" X="-476.363321587537" Y="-8.67834747774475" zoom="0.97676875" ScaleFactor="1" Name="Get_Viewport_MinPoint" Description="get the viewport min point from input viewports" ID="877e33ac-13bf-4352-99fa-0da9cf582a7b" Category="ArupBimSF.Revit.Views &amp; Sheets">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="a1519b91-376d-4923-9114-821aee92a146" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1238.57041373594" y="401.519287833828" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

viewports = IN[0]

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

def GetLocation(v):
	v = UnwrapElement(v)
	outline = v.GetBoxOutline()
	return outline.MinimumPoint.ToPoint()

#Assign your output to the OUT variable.
OUT = ProcessList(GetLocation, viewports)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a3ad2cf7-9484-485d-9a84-e8c3d2be1ce1" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1424.91686741062" y="506.191565201887" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="MinPoint" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="978d6595-a95b-4c56-9fa0-a2d81a9f8b14" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1089.91097922849" y="505.219124307309" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Viewport" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a1519b91-376d-4923-9114-821aee92a146" start_index="0" end="a3ad2cf7-9484-485d-9a84-e8c3d2be1ce1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="978d6595-a95b-4c56-9fa0-a2d81a9f8b14" start_index="0" end="a1519b91-376d-4923-9114-821aee92a146" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>