<Workspace Version="1.3.2.2480" X="35.385" Y="59.625" zoom="0.8425" ScaleFactor="1" Name="Get_ActiveView" Description="captures your active view and keeps it as an input " ID="74606960-673b-44ec-bbbe-a9c4cc82b7d5" Category="ArupBimSF.Revit.Views &amp; Sheets">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ee234570-771a-45a1-9abe-9153a5e26453" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1196.63384840192" y="517.66712655963" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="241bf623-ebaa-4ff6-a187-890bde9332d1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="536.094372272176" y="314.198716921637" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitNodes
clr.AddReference("RevitNodes")
import Revit

# Import Revit elements
from Revit.Elements import *

# Import DocumentManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

import System

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
uidoc = uiapp.ActiveUIDocument
app = uiapp.Application
view = uidoc.ActiveView 

OUT = view</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="45aa970e-1a21-4fd7-888f-30bc01abf6cb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="457.839762611276" y="427.471810089021" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Refresh : bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="25347eb8-4fb5-49af-b4fb-18d422c22272" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="782" y="458" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="list;&#xA;come;&#xA;&#xA;[Imperative]&#xA;&#xA;{&#xA;	if (come ==true)&#xA;		return = list;&#xA;	else&#xA;		return = list;&#xA;};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="241bf623-ebaa-4ff6-a187-890bde9332d1" start_index="0" end="25347eb8-4fb5-49af-b4fb-18d422c22272" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="45aa970e-1a21-4fd7-888f-30bc01abf6cb" start_index="0" end="25347eb8-4fb5-49af-b4fb-18d422c22272" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="25347eb8-4fb5-49af-b4fb-18d422c22272" start_index="2" end="ee234570-771a-45a1-9abe-9153a5e26453" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>