<Workspace Version="1.3.2.2480" X="-626.724978330797" Y="717.415669599865" zoom="0.719702865877913" ScaleFactor="1" Name="Image_FromDirectoryâžœDraftingView" Description="imports images from a directory and places them on drafting views" ID="aec4aebf-005b-4bec-8ce3-a30c372e5ac7" Category="ArupBimSF.Revit.Links &amp; Imports">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="402d53d6-82bd-4759-b908-d6d0fdbfc99e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="DraftingView.ByName" x="1838.76780757023" y="-593.362377352536" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Views.DraftingView.ByName@string">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.BoolSelector guid="6bb91c80-2767-4d39-a55c-38f9e5733e10" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="1883.99648712348" y="-280.98588727644" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <PythonNodeModels.PythonNode guid="1bcfaa75-ba8a-4ae4-acb3-b14e9f038570" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1868.93351707679" y="-438.768584848761" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Revit API
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

placement = IN[0]
refPt = IN[1]
res = IN[2]

iio = ImageImportOptions()

def toRvtPoint(point):
	x = point.X
	y = point.Y
	z = point.Z
	return XYZ(x,y,z,)
	
message = None
if placement != None:
	iio.Placement = placement
if refPt != None:
	iio.RefPoint = toRvtPoint(refPt)
else:
	message = "Please specify placement point."
if res != None:
	iio.Resolution - res
else:
	iio.Resolution - 72
	
# Assign your output to the OUT variable
OUT = iio</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="2c30adb7-2b4c-431f-b1ed-b551e21d9d04" type="CoreNodeModels.Watch" nickname="Watch" x="2528.02520713674" y="-333.237384297097" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9e834aaa-4c02-482e-9eb1-a2ff171fd0f4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FilePath.FileName" x="1423.26308442152" y="-669.932697177108" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.IO.FilePath.FileName@string,bool">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c5fada73-4deb-48d8-bc1c-59765c8d6d97" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1456.99648712348" y="-300.982170965974" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Autodesk.Point.ByCoordinates(0,0,0);&#xA;72;" ShouldFocus="false" />
    <CoreNodeModels.Input.BoolSelector guid="4c28bb25-cde9-4d18-bda4-261b4a9187fd" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="1145.99648712348" y="-478.908837632641" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>False</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <CoreNodeModels.Watch guid="0ee63a92-7ba0-40fa-b896-7b6556e03773" type="CoreNodeModels.Watch" nickname="Watch" x="2032.36517799851" y="-808.947054855591" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <PythonNodeModels.PythonNode guid="41af84b1-256c-4c30-a0d2-ef875dcdc5f3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1135.1147443164" y="-759.030208160157" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="0">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

#Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
import System

#Assign your output to the OUT variable
OUT = System.Enum.GetValues(BoxPlacement)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c781872d-fe60-43f6-92a3-6ce465a78e49" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="1474.40727561481" y="-459.260497527518" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a48f457c-6ed8-4b64-8f75-dd5c2bacea64" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="2439.99648712348" y="-679.908837632641" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="PositionOpts" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="effe6817-9c81-4cd4-878f-2c0aaf790291" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="2439.99648712348" y="-513.908837632641" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="View_Names" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="09d8e611-5d34-4089-ac5e-dfa409918a45" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="2439.99648712348" y="-596.908837632641" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="View_Elem" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a530141c-2495-429e-a31a-6a198f1f66c9" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="2439.99648712348" y="-430.908837632641" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Image_Elem" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6f2228c4-cf92-4ef7-bfe4-bcbffdeb8b48" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1145.99648712348" y="-646.908837632641" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FilePaths" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="242969ea-1f27-42a3-8e4a-89a5ee341e07" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1118.79213010577" y="-362.763609211388" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Position_Opt : int = 4" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="2a839459-e855-45c6-9c53-8001fcc8c9cb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2233.21604379689" y="-452.387847958984" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>#Copyright(c) 2016, Cesare Caoduro
# http://bimandothers.blogspot.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

#Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

filePath= IN[0]
iio = IN[1]
view = UnwrapElement(IN[2])
RunIt = IN[3]

images = []
if RunIt:
	# Start Transaction
	TransactionManager.Instance.EnsureInTransaction(doc)
	for path1, view1 in zip(filePath, view):
		newElement = clr.StrongBox[Element]()
		doc.Import(path1, iio, view1, newElement)
		images.append(newElement.Value)	
	# End Transaction
	TransactionManager.Instance.TransactionTaskDone()
	message = "Success!"
else:
	message = "Set RunIt to True."
	
# Assign your output to the OUT variable
if message == "Success!":
	OUT = images
else:
	OUT = message</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="402d53d6-82bd-4759-b908-d6d0fdbfc99e" start_index="0" end="09d8e611-5d34-4089-ac5e-dfa409918a45" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="402d53d6-82bd-4759-b908-d6d0fdbfc99e" start_index="0" end="2a839459-e855-45c6-9c53-8001fcc8c9cb" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6bb91c80-2767-4d39-a55c-38f9e5733e10" start_index="0" end="2a839459-e855-45c6-9c53-8001fcc8c9cb" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1bcfaa75-ba8a-4ae4-acb3-b14e9f038570" start_index="0" end="2c30adb7-2b4c-431f-b1ed-b551e21d9d04" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1bcfaa75-ba8a-4ae4-acb3-b14e9f038570" start_index="0" end="2a839459-e855-45c6-9c53-8001fcc8c9cb" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9e834aaa-4c02-482e-9eb1-a2ff171fd0f4" start_index="0" end="402d53d6-82bd-4759-b908-d6d0fdbfc99e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9e834aaa-4c02-482e-9eb1-a2ff171fd0f4" start_index="0" end="effe6817-9c81-4cd4-878f-2c0aaf790291" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c5fada73-4deb-48d8-bc1c-59765c8d6d97" start_index="0" end="1bcfaa75-ba8a-4ae4-acb3-b14e9f038570" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c5fada73-4deb-48d8-bc1c-59765c8d6d97" start_index="1" end="1bcfaa75-ba8a-4ae4-acb3-b14e9f038570" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4c28bb25-cde9-4d18-bda4-261b4a9187fd" start_index="0" end="9e834aaa-4c02-482e-9eb1-a2ff171fd0f4" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ee63a92-7ba0-40fa-b896-7b6556e03773" start_index="0" end="a48f457c-6ed8-4b64-8f75-dd5c2bacea64" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="41af84b1-256c-4c30-a0d2-ef875dcdc5f3" start_index="0" end="0ee63a92-7ba0-40fa-b896-7b6556e03773" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="41af84b1-256c-4c30-a0d2-ef875dcdc5f3" start_index="0" end="c781872d-fe60-43f6-92a3-6ce465a78e49" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c781872d-fe60-43f6-92a3-6ce465a78e49" start_index="0" end="1bcfaa75-ba8a-4ae4-acb3-b14e9f038570" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6f2228c4-cf92-4ef7-bfe4-bcbffdeb8b48" start_index="0" end="9e834aaa-4c02-482e-9eb1-a2ff171fd0f4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6f2228c4-cf92-4ef7-bfe4-bcbffdeb8b48" start_index="0" end="2a839459-e855-45c6-9c53-8001fcc8c9cb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="242969ea-1f27-42a3-8e4a-89a5ee341e07" start_index="0" end="c781872d-fe60-43f6-92a3-6ce465a78e49" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a839459-e855-45c6-9c53-8001fcc8c9cb" start_index="0" end="a530141c-2495-429e-a31a-6a198f1f66c9" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>