<Workspace Version="1.3.2.2480" X="-859.797762583657" Y="-76.176257489803" zoom="1.00600419002725" ScaleFactor="1" Name="LineStyle_CreateNew" Description="Create new linestyles by color, weight and name" ID="87d5235e-9138-49f3-83ff-5fa6acbcde24" Category="ArupBimSF.Revit.Lines,Text &amp; Styles">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9da8fd37-a999-49fb-b02e-01d1be1994f7" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1945.09389394718" y="453.573788400789" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="LineStyles" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="1c93f9f4-04c1-473e-b579-d6db57de4027" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1657.66145533464" y="442.298385964013" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TextBox
from Autodesk.Revit.UI import TaskDialog
from Autodesk.Revit.UI import TaskDialogCommonButtons

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

def convertToList(testList):
	if isinstance(testList, list):
		return testList
	else:
		return [testList]
				
def convertToListOfLists(testColourList):
	msgTitle = "Colour data structure error"
	msgMessage = "The Line Style colours are not in sublists. Each RGB colour set should be defined in a sublist, eg: { {red, green, blue} }"
	if isinstance(testColourList, list): 
		if isinstance(testColourList[0], list):
			
			for i in testColourList: 
				if isinstance(i, list) and len(i) == 3:
					continue
				else: 
					TaskDialog.Show(msgTitle, msgMessage, TaskDialogCommonButtons.Ok)
					testColourList = True
					return testColourList
					
			return testColourList 
				
		else:
			if len(testColourList) == 3: 
				return [testColourList]
			else: 
				TaskDialog.Show(msgTitle, msgMessage, TaskDialogCommonButtons.Ok)
				testColourList = True
				return testColourList
	else:
		TaskDialog.Show(msgTitle, msgMessage, TaskDialogCommonButtons.Ok)
		testColourList = True
		return testColourList
			
run = IN[3]

if run:
	lineStylesName =  convertToList( IN[0] )
	lineStylesWeight =  convertToList( IN[1] )
	lineStylesColour = convertToListOfLists( IN[2] )
	if lineStylesColour == True:
		OUT = "Colour data structure error - colours should be input as integer sublists defining the RGB values"
	else:
		listLacingCheck = False 
		if len(lineStylesName) == len(lineStylesWeight) == len(lineStylesColour):
			listLacingCheck = True
		else:
			TaskDialog.Show("Lacing error", "The number of items in the name, line weight and line colours input lists do not match. Ensure there are an equal number of items in each list and try again", TaskDialogCommonButtons.Ok)
			OUT = "Lacing mismatch - ensure an equal number of items are in each input"
		
		if listLacingCheck:
			TransactionManager.Instance.EnsureInTransaction(doc)
			doc.Regenerate()
			
			categories = doc.Settings.Categories
			lineCategory =  doc.Settings.Categories.get_Item( BuiltInCategory.OST_Lines )
			lineSubCategory = lineCategory.SubCategories
			
			newLineStyleList = zip(lineStylesName, lineStylesWeight, lineStylesColour)
			
			errorReport = []
			for lineStyleData in newLineStyleList:
				try:
					inProject = False
					name = lineStyleData[0]
					for i in lineSubCategory:
						if i.Name == name:
							inProject = True
							errorReport.Add( "LineStyle " + name + " exists in the current document and cannot be created")
							break
					if inProject:
						continue
					else:
						newLineStyle = categories.NewSubcategory(lineCategory, name);
						newLineStyle.LineColor = Color(lineStyleData[2][0], lineStyleData[2][1], lineStyleData[2][2]);
						newLineStyle.SetLineWeight(lineStyleData[1], GraphicsStyleType.Projection);
					
				except:
					errorReport.Add( "LineStyle creation failed Check your data types are correctly wired to the node and retry" )
			
			TransactionManager.Instance.TransactionTaskDone()
			
			if errorReport == []:
				OUT = "All LineStyles successfully created"
			else:
				OUT = errorReport</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="efdc7a39-52c4-437b-8e9e-92ce90d52106" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1067.97583459053" y="438" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Provide a list of strings to name each new Line Style&#xD;&#xA;LS_Name:string[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c3fefe93-28e4-463e-91bb-3582405d1b37" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1039.57805609616" y="510.474297872208" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Add the line wieghts for the new Line Styles as integers&#xD;&#xA;LS_Weight:int[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2ac38430-5915-4628-918f-9488e968ff71" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="862.5" y="585.445756161008" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Add a list of RGB integer values for each Line Style. The values should be structured into sublists&#xD;&#xA;LS_Color:int[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f2d3dae1-9118-4f4c-a998-bcd88e17d2d1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1158.17839225796" y="692.269087248801" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Set to True to create the new Line Styles&#xD;&#xA;RunMe:bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1c93f9f4-04c1-473e-b579-d6db57de4027" start_index="0" end="9da8fd37-a999-49fb-b02e-01d1be1994f7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="efdc7a39-52c4-437b-8e9e-92ce90d52106" start_index="0" end="1c93f9f4-04c1-473e-b579-d6db57de4027" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c3fefe93-28e4-463e-91bb-3582405d1b37" start_index="0" end="1c93f9f4-04c1-473e-b579-d6db57de4027" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2ac38430-5915-4628-918f-9488e968ff71" start_index="0" end="1c93f9f4-04c1-473e-b579-d6db57de4027" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f2d3dae1-9118-4f4c-a998-bcd88e17d2d1" start_index="0" end="1c93f9f4-04c1-473e-b579-d6db57de4027" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>