<Workspace Version="1.3.2.2480" X="-348" Y="-49" zoom="1" ScaleFactor="1" Name="MepSystem_Add Element" Description="add an input element to mep system" ID="b33b4792-e065-41b8-9ffc-ab9dbe416154" Category="ArupBimSF.Revit.Mep">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f568e941-9aa6-4421-b6af-e8cee5d37a0e" type="PythonNodeModels.PythonNode" nickname="Python: AddToSystem" x="967.5" y="445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)


def AddToSystem(sys,terminals):
	result = []
	systype = sys.SystemType
	if systype.GetType() == Mechanical.DuctSystemType:
		TransactionManager.Instance.EnsureInTransaction(doc)
		if hasattr(terminals, "__iter__"):
			for terminal in terminals:
				try:
					connectors = terminal.MEPModel.ConnectorManager.Connectors
					for conn in connectors:
						try:
							if conn.DuctSystemType == systype:
								connset = ConnectorSet()
								connset.Insert(conn)
								sys.Add(connset)
								result.append(terminal)
						except:
							pass
				except:
					pass
		else:
			try:
				connectors = terminal.MEPModel.ConnectorManager.Connectors
				for conn in connectors:
					try:
						if conn.DuctSystemType == systype:
							connset = ConnectorSet()
							connset.Insert(conn)
							sys.Add(connset)
							result.append(terminal)
					except:
						pass
			except:
				pass
		TransactionManager.Instance.TransactionTaskDone()
	else:
		TransactionManager.Instance.EnsureInTransaction(doc)
		if hasattr(terminals, "__iter__"):
			for terminal in terminals:
				try:
					connectors = terminal.MEPModel.ConnectorManager.Connectors
					for conn in connectors:
						try:
							if conn.PipeSystemType == systype:
								connset = ConnectorSet()
								connset.Insert(conn)
								sys.Add(connset)
								result.append(terminal)
						except:
							pass
				except:
					pass
		else:
			try:
				connectors = terminal.MEPModel.ConnectorManager.Connectors
				for conn in connectors:
					try:
						if conn.PipeSystemType == systype:
							connset = ConnectorSet()
							connset.Insert(conn)
							sys.Add(connset)
							result.append(terminal)
					except:
						pass
			except:
				pass
		TransactionManager.Instance.TransactionTaskDone()
	return result

listout = []
if isinstance(IN[0], list):
	for i,sys in enumerate(UnwrapElement(IN[0])):
		listout.append(AddToSystem(sys,UnwrapElement(IN[1])[i]))
else:
	listout.append(AddToSystem(UnwrapElement(IN[0]),UnwrapElement(IN[1])))

OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a987917a-5b8d-48fd-b16b-545bec388e45" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1212.5" y="444" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Result" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a9f00133-28a2-4ca1-b072-b8ae199fc6d1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="754.5" y="438" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="System" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9ff20792-2e1d-4cd4-a046-bc2d2a23abcd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="728.5" y="549" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f568e941-9aa6-4421-b6af-e8cee5d37a0e" start_index="0" end="a987917a-5b8d-48fd-b16b-545bec388e45" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a9f00133-28a2-4ca1-b072-b8ae199fc6d1" start_index="0" end="f568e941-9aa6-4421-b6af-e8cee5d37a0e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9ff20792-2e1d-4cd4-a046-bc2d2a23abcd" start_index="0" end="f568e941-9aa6-4421-b6af-e8cee5d37a0e" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>