<Workspace Version="1.3.2.2480" X="-91" Y="204" zoom="1" ScaleFactor="1" Name="PolyCurve_ThroughPoints" Description="creates a closed curve throuh input points" ID="2b89892e-95f8-4fc4-8e89-d4ba43df6b2a" Category="ArupBimSF.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3782c55f-e6f1-47af-bc36-e2c659c4f1a4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="406" y="312.147894328524" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="points : Autodesk.Point[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e4b080f2-3b89-42fa-aee9-c0ecc6e36480" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1234" y="312.147894328524" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Curves" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="332de336-a5f7-47c3-8075-17fd85ffb085" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="718.974687882579" y="273" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="PolyCurve.ByPoints(plist,true).Curves();" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3782c55f-e6f1-47af-bc36-e2c659c4f1a4" start_index="0" end="332de336-a5f7-47c3-8075-17fd85ffb085" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="332de336-a5f7-47c3-8075-17fd85ffb085" start_index="0" end="e4b080f2-3b89-42fa-aee9-c0ecc6e36480" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>