<Workspace Version="1.3.2.2480" X="-860.040389796814" Y="-40.4442254669626" zoom="1.05429821501133" ScaleFactor="1" Name="Sched_Get Data" Description="GEt revit Schedule Data as output" ID="9f153651-c15a-4efb-a8bf-e9557ddd0243" Category="ArupBimSF.Revit.Views &amp; Sheets">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6bc124cc-d7c4-4c37-80d5-eeeb4c850901" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1640.16024869437" y="411.974189506942" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

scheduleName = IN[0]
removeHeadings = IN[1]

collector = FilteredElementCollector(doc)
collector.OfClass( ViewSchedule );
elementlist = collector.ToElements()

if isinstance(scheduleName, str):
	schedule = None
	for i in elementlist:
		scheduleViewName = BuiltInParameter.VIEW_NAME
		viewName = i.get_Parameter( scheduleViewName ).AsString()
		
		if viewName == scheduleName:
			schedule = i
			break
else:
	schedule = UnwrapElement(scheduleName)

table = schedule.GetTableData().GetSectionData(SectionType.Body)
nRows = table.NumberOfRows
nColumns = table.NumberOfColumns

dataListRow = []
for row in range(nRows): 
	dataListColumn = []
	for column in range(nColumns):
		dataListColumn.Add( TableView.GetCellText(schedule, SectionType.Body, row, column) )
	dataListRow.Add( dataListColumn );

if removeHeadings:
	OUT = dataListRow[2:]
else:
	OUT = dataListRow</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="52b9bc44-d795-48c4-95dc-8280ca3f004d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1847.52204227232" y="417.993506101747" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Sched_Data" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="25d07261-3e7d-427f-8208-f3b8acb74401" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="905.182420741381" y="401.008568690803" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Enter the Revit schedule view or the schedule name as a string. Name is case-sensitive&#xD;&#xA;Sched_ViewOrName:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="06591819-db9e-4917-a842-e82725a52ce1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1003.9278168478" y="495.918611092716" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Set to True to remove the headings from the collected schedule data&#xD;&#xA;Remove_Headings:bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6bc124cc-d7c4-4c37-80d5-eeeb4c850901" start_index="0" end="52b9bc44-d795-48c4-95dc-8280ca3f004d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="25d07261-3e7d-427f-8208-f3b8acb74401" start_index="0" end="6bc124cc-d7c4-4c37-80d5-eeeb4c850901" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="06591819-db9e-4917-a842-e82725a52ce1" start_index="0" end="6bc124cc-d7c4-4c37-80d5-eeeb4c850901" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>