<Workspace Version="1.3.2.2480" X="-363" Y="60" zoom="1" ScaleFactor="1" Name="Set_ElectricalSystemName_ToElements" Description="Sets an electrical system name to elements " ID="a14fd5fa-b81d-4d87-aa39-6091ca6345a1" Category="ArupBimSF.Revit.Mep_Electrical">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="a474d7bc-2fc5-4f72-860e-92f33f6e8927" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1240.78632261423" y="283" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument




element = UnwrapElement(IN[0])
pname = IN[1]


def SetValueToElementParameterByName(e, en, ev):
		params = e.Parameters
		for param in params:
			if param.Definition.Name == en:
				try:
					t= Transaction(doc)
					t.Start("Set value to parameter")
					param.Set(ev)	
					t.Commit();
				except:
					pass
pass


def getSystem(elem):
	system = elem.MEPModel.ElectricalSystems
	
	if system.Size == 0:
		return None
	elif system.Size == 1:	
		for sys in system:
			return sys
	else:
		for sys in system:
			return sys
		

listout = []	

for x in element:
	try:
		system = getSystem(x)			
		param = system.get_Parameter(BuiltInParameter.RBS_ELEC_CIRCUIT_NUMBER).AsString()	
		SetValueToElementParameterByName(x, pname, param)			
		listout.append(x)			
	except:
		listout.append(None)

OUT = listout
	
	
	
	
	</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4a616b67-78a9-4dbe-b016-f4aebf946e28" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="764.286322614226" y="285.481145974994" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0abd8d72-f8c0-4166-910f-1aaa7423aa7a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="444" y="360.582823564687" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="parameterName: string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="100c12a5-32aa-421a-8603-e9b91eac08eb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1470.28632261423" y="297.481145974994" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b67630ac-5277-4db6-abe2-8512fc3fc06c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="687.5343633447" y="435.961097373378" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="refresh:bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a474d7bc-2fc5-4f72-860e-92f33f6e8927" start_index="0" end="100c12a5-32aa-421a-8603-e9b91eac08eb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a616b67-78a9-4dbe-b016-f4aebf946e28" start_index="0" end="a474d7bc-2fc5-4f72-860e-92f33f6e8927" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0abd8d72-f8c0-4166-910f-1aaa7423aa7a" start_index="0" end="a474d7bc-2fc5-4f72-860e-92f33f6e8927" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b67630ac-5277-4db6-abe2-8512fc3fc06c" start_index="0" end="a474d7bc-2fc5-4f72-860e-92f33f6e8927" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>