<Workspace Version="1.3.2.2480" X="-153.257149068485" Y="149.553560184588" zoom="0.593767140625" ScaleFactor="1" Name="UnLoad_Fabrication_Services" Description="unloads fab services from active doc" ID="0ffd563d-14e9-4a82-9eb0-ff65fec74b61" Category="ArupBimSF.Revit.Fabrication">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="992cd772-4316-40a4-ba28-86812738b15e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1336.84147728762" y="245.283348805634" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Service_IDsRemoved" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="5caebc66-546b-48ae-9452-2fd54460d444" type="PythonNodeModels.PythonNode" nickname="Fabrication Service(s) ID" x="1126.02961147175" y="253.16285288954" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

ItmList.append(Inpt)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="2b695521-67c1-4a95-a395-0813b9144ee1" type="PythonNodeModels.PythonNode" nickname="Fabrication UnLoad Service(s)" x="1111.54669792449" y="390.249072106137" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

Inpt = UnwrapElement(IN[0])
ItmList= list()

Doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(Doc)

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)
Config.ReloadConfiguration()
UnLServices = Config.UnloadServices(Inpt)
ItmList.append(Inpt)

TransactionManager.Instance.TransactionTaskDone()

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="dbc7b30a-5c7a-4aa1-b466-faad2f9d8e2f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="912.655874574168" y="311.129481545136" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Service_IDs" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5caebc66-546b-48ae-9452-2fd54460d444" start_index="0" end="992cd772-4316-40a4-ba28-86812738b15e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dbc7b30a-5c7a-4aa1-b466-faad2f9d8e2f" start_index="0" end="5caebc66-546b-48ae-9452-2fd54460d444" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dbc7b30a-5c7a-4aa1-b466-faad2f9d8e2f" start_index="0" end="2b695521-67c1-4a95-a395-0813b9144ee1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>