<Workspace Version="1.3.2.2480" X="-4.46112220572354" Y="138.207501147408" zoom="0.97676875" ScaleFactor="1" Name="Viewport_Get Center Point" Description="get the centerpoint of input views" ID="e096b407-8bae-45f3-a12e-d555fa3780d7" Category="ArupBimSF.Revit.ViewPorts and Boundaries">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d0c85eab-d0a7-47b1-89f6-4a448d03a764" type="PythonNodeModels.PythonNode" nickname="Python Script" x="773" y="20" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

elt = []
for i in IN[0]:
	elt.append(UnwrapElement(i))

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)
loc=[]
for v in elt:
	loc.append(v.GetBoxCenter().ToPoint())

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT=loc</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="df67385c-1b7d-49b7-80fe-7775c325b22a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="997" y="20" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Points" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1a6d4b70-3683-449a-8bf8-514b8b2a61d4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="548" y="20" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Viewports" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d0c85eab-d0a7-47b1-89f6-4a448d03a764" start_index="0" end="df67385c-1b7d-49b7-80fe-7775c325b22a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1a6d4b70-3683-449a-8bf8-514b8b2a61d4" start_index="0" end="d0c85eab-d0a7-47b1-89f6-4a448d03a764" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>